services:
  db:
    container_name: my_home_page_db
    image: postgres:15.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  web:
    container_name: my_home_page
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_home_page
    ports:
      - "3000:3000"
    depends_on:
      - db